language: ruby
rvm:
- 2.2.5
deploy:
  provider: heroku
  api_key:
    secure: amU3ZqbwM1QjYa0lbVrB5EQeKemBZg0tYPH80ULKLnTRdMuraXvCju9C/aq5rC0inSBeiqb/zdydKi5kkKqYY8JfuaPMWRzLz4or8dJWuqK4f/RE0WKQ4t1nByqhMsZfGaDpIyfmjWRpTcZLeh8Oyqyq5IHh49QVCvLIZ4NXhkHWwBACc7M1ZGfFNPlnNmRv40tXY4qOZZRCPKBhuKGXTfdz/TIX2VX/rej0o90ALk7KWPhfU/YW1m9ugzDjT0+GCwTIE/eqJJQVQpz0KToqtz0Y6aIVteLoddCkx25XwJMXtNCJqu5wsm8SB/DrMX6P7rQgPjAg81MP1fZIao/rg1Ljuoe/lAld5Y2pR7mcYwa1b+xDFAvstFuCFDSMHmcDoySyEc5/X8PIiiUEnanuibovUIBKWqAlWyi0X6OdEW4VwnA0Lj44NufMt/YjHUwIctWDDnHmoVxOkANyXZ21mO73JuvEAuzHVCEeHkDYOJhGlcpGYbOY5H9kr49I/m7Dq1ZjsyK4/kSx6y3snljqDfnnZ8rTHlrhsMKxxQIZ8dlXIXZRTssv321EH/4MGZ1b7uYm0xy2QabdJUJ1oKI+NK5Pt228+a/mpx4oTfRkrSlFHLaRXWrKrAnMhCqQfEqr7z85qatMWKBQ64uD2ysyJl9L5g0T0szrtMV3ZHb07co=
  app: itswitter
  on:
    repo: ryupitbros4/itswitter
